console.log("DC LOADED");
var BACKEND_URL = "https://dark-connector-production.up.railway.app";
var KNOWN_TRACKERS={"facebook.net":"Facebook Pixel active","google-analytics.com":"Google Analytics active","hotjar.com":"Hotjar recording active","clarity.ms":"Clarity recording active","criteo.com":"Criteo tracker active"};
function detectPreTickedCheckboxes(){var r=[];document.querySelectorAll("input[type=checkbox]:checked").forEach(function(el){var l=document.querySelector("label[for='"+el.id+"']")||el.closest("label");var t=l?l.innerText.toLowerCase():"";if(["newsletter","subscribe","offers","insurance","marketing"].some(function(w){return t.includes(w);})){r.push({element:el,pattern:"pre_ticked_checkbox",confidence:0.92,message:"Pre-ticked Checkbox"});}});return r;}
function detectCountdownTimers(){var r=[];["[class*=timer]","[class*=countdown]","[id*=timer]","[id*=countdown]"].forEach(function(s){try{document.querySelectorAll(s).forEach(function(el){r.push({element:el,pattern:"fake_countdown",confidence:0.85,message:"Countdown Timer"});});}catch(e){}});return r;}
function detectConfirmshaming(){var r=[];var p=["no thanks, i hate","no thanks, i don","i don't want to save","nahi chahiye"];document.querySelectorAll("a,button,label,span").forEach(function(el){var t=(el.innerText||"").toLowerCase().trim();if(t&&t.length<100&&p.some(function(x){return t.includes(x);})){r.push({element:el,pattern:"confirmshaming",confidence:0.94,message:"Confirmshaming"});}});return r;}
function detectVisualInterference(){var r=[];var a=["accept","accept all","agree","allow all"];var b=["reject","reject all","decline","necessary only"];var btns=Array.from(document.querySelectorAll("button,a[role=button]"));var ab=null,rb=null;btns.forEach(function(x){var t=(x.innerText||"").toLowerCase().trim();if(a.indexOf(t)>-1)ab=x;if(b.indexOf(t)>-1)rb=x;});if(ab&&rb){var as=parseFloat(window.getComputedStyle(ab).fontSize)||14;var rs=parseFloat(window.getComputedStyle(rb).fontSize)||14;if(as>rs*1.3)r.push({element:rb,pattern:"visual_interference",confidence:0.88,message:"Visual Interference"});}return r;}
function detectFakeUrgency(){var r=[];var p=[/only \d+ (rooms?|left|seats?)/i,/we have \d+ left/i,/selling fast/i,/in high demand/i,/sirf \d+ (bacha|left)/i];document.querySelectorAll("p,span,div,strong,small").forEach(function(el){var t=(el.innerText||"").trim();if(t.length>0&&t.length<200&&p.some(function(x){return x.test(t);})){r.push({element:el,pattern:"fake_urgency",confidence:0.82,message:"Fake Urgency"});}});return r;}
function detectSocialProof(){var r=[];var p=[/\d+ (people|guests?) (just )?(booked|viewed)/i,/someone just booked/i,/\d+ (are )?viewing this/i];document.querySelectorAll("p,span,div,small").forEach(function(el){var t=(el.innerText||"").trim();if(t.length>0&&t.length<150&&p.some(function(x){return x.test(t);})){r.push({element:el,pattern:"social_proof_manipulation",confidence:0.79,message:"Fake Social Proof"});}});return r;}
function detectTrackers(){var r=[];document.querySelectorAll("script[src]").forEach(function(el){var s=(el.src||"").toLowerCase();Object.keys(KNOWN_TRACKERS).forEach(function(d){if(s.includes(d))r.push({element:el,pattern:"privacy_zuckering",confidence:0.98,message:KNOWN_TRACKERS[d]});});});return r;}
function highlightElement(el,msg,pat){if(!el||el.dataset.dcFlagged==="true")return;el.dataset.dcFlagged="true";el.style.outline="2px solid #FF3B3B";el.style.outlineOffset="2px";if(window.getComputedStyle(el).position==="static")el.style.position="relative";var t=document.createElement("div");t.className="dc-tooltip";t.innerText="⚠️ "+msg;el.appendChild(t);}
function sendToBackend(results){chrome.storage.local.get("analyticsConsent",function(s){if(s.analyticsConsent!==true)return;try{fetch(BACKEND_URL+"/api/report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({site_url:window.location.hostname,patterns:results.map(function(r){return{pattern_type:r.pattern,confidence:r.confidence};}),confirmed:false})}).catch(function(){});}catch(e){}});}
function runDetection(){var all=[].concat(detectPreTickedCheckboxes(),detectCountdownTimers(),detectConfirmshaming(),detectVisualInterference(),detectFakeUrgency(),detectSocialProof(),detectTrackers());var seen=new Map();all.forEach(function(r){if(!r.element)return;if(!seen.has(r.element)||seen.get(r.element).confidence<r.confidence)seen.set(r.element,r);});var u=Array.from(seen.values());u.forEach(function(r){highlightElement(r.element,r.message,r.pattern);});if(u.length>0){try{chrome.runtime.sendMessage({type:"DETECTION_RESULTS",results:u.map(function(r){return{pattern:r.pattern,confidence:r.confidence,message:r.message};}),url:window.location.hostname});}catch(e){}sendToBackend(u);}}
var _t=null;var obs=new MutationObserver(function(m){if(!m.some(function(x){return x.addedNodes&&x.addedNodes.length>3;}))return;clearTimeout(_t);_t=setTimeout(runDetection,2000);});obs.observe(document.body||document.documentElement,{childList:true,subtree:true,attributes:false,characterData:false});
if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",runDetection);}else{runDetection();}